#!/bin/sh
set -e

case "$1" in
  configure)
    case "`uname -s`" in
      Linux)
        # Pre-wheezy versions of the package shipped a symlink from
        # /etc/modprobe.d to /lib/oss-compat, so when upgrading and
        # finding a symlink we must replace the link with a copy.
        # The wheezy version of the package shipped a configuration
        # file with md5sum 88222606b0a3ba8b0825c5000c754e6f which
        # should be replaced with the new file.
        # Anything else must be left alone (policy requires changes
        # to configuration to be preserved).
        curconffile=/etc/modprobe.d/oss-compat.conf
        oldconffile=/etc/modprobe.d/oss-compat
        if [ ! -f ${curconffile} -o -L ${curconffile} ]; then
          if [ -L ${curconffile} ]; then
            # Upgrading from .conf link
            curlinktgt=$(readlink -f ${curconffile})
            rm -f ${curconffile}
            cp ${curlinktgt} ${curconffile}
          elif [ -L ${oldconffile} ]; then
            # Upgrading from extension-less link
            curlinktgt=$(readlink -f ${oldconffile})
            cp ${curlinktgt} ${curconffile}
          elif [ -f ${oldconffile} ]; then
            # Upgrading from extension-less file
            cp ${oldconffile} ${curconffile}
          else
            # Installing from scratch
            cp /lib/oss-compat/linux ${curconffile}
          fi
        fi
        # Cleanup extension-less configuration link
        [ -L ${oldconffile} ] && rm -f ${oldconffile}
        # Wheezy configuration file (using install directives)
        [ -f ${curconffile} ] && [ "$(md5sum ${curconffile} | cut -d\  -f1)" = "88222606b0a3ba8b0825c5000c754e6f" ] && cp /lib/oss-compat/linux ${curconffile}

        if lsmod | grep -q "^snd " ; then
          modprobe snd || true
        fi
      ;;
    esac
  ;;
  abort-upgrade|abort-remove|abort-deconfigure)
  ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

#DEBHELPER#

exit 0
